"""compose_build - Build images for services with build contexts."""

from utils import (
    resolve_compose_path,
    parse_compose,
    prepare_compose,
    get_build_services,
    get_unit_directory,
    run_cmd,
)


def compose_build(compose_file: str | None = None, **_kwargs) -> None:
    """Build images using quadlet .build units generated by podlet.

    Regenerates quadlet files (including .build units), reloads systemd,
    and starts the build services.
    """
    compose_path = resolve_compose_path(compose_file)
    compose_data = parse_compose(compose_path)
    services = get_build_services(compose_data)

    if not services:
        print("No services with build contexts found.")
        return

    project = compose_data["project"]
    podlet_input = prepare_compose(compose_path)
    compose_dir = str(compose_path.parent.resolve())

    get_unit_directory()
    run_cmd(
        [
            "podlet",
            "--unit-directory",
            "--overwrite",
            "--skip-services-check",
            f"--absolute-host-paths={compose_dir}",
            "compose",
            "--pod",
            str(podlet_input),
        ],
        quiet=True,
    )

    run_cmd(["systemctl", "--user", "daemon-reload"], quiet=True)

    targets = [f"{project}-{svc}" for svc in services]

    def build_target(target):
        run_cmd(["systemctl", "--user", "restart", f"{target}.service"])

    from utils.progress import run_with_progress

    run_with_progress(targets, build_target, "Built")
