"""compose_convert - Preview quadlet files without installing."""

from utils import resolve_compose_path, run_cmd


def compose_convert(
    compose_file: str | None = None, kube: bool = False, **_kwargs
) -> None:
    """Preview the quadlet files that would be generated by podlet.

    Runs podlet compose without --unit-directory so output goes to stdout.
    Uses the same defaults as up (--pod, --overwrite, --absolute-host-paths).
    """
    compose_path = resolve_compose_path(compose_file)

    # Build the same command as up, but without --unit-directory.
    # options and must precede the "compose" subcommand.
    cmd = [
        "podlet",
        "--overwrite",
        "--absolute-host-paths",
        "compose",
    ]
    if kube:
        cmd.append("--kube")
    else:
        cmd.append("--pod")
    cmd.append(str(compose_path))

    result = run_cmd(cmd)
    if result.stdout:
        print(result.stdout, end="")
