"""compose_down - Stop services managed by quadlet files from compose.yaml."""

from utils import (
    get_unit_directory,
    resolve_compose_path,
    parse_compose,
    get_service_targets,
    run_cmd,
)
from utils.progress import run_with_progress


def compose_down(
    compose_file: str | None = None, remove_files: bool = False, **_kwargs
) -> None:
    """Stop systemd services and optionally remove quadlet files.

    Stops services using the appropriate target (pod, kube, or individual).
    If remove_files is True, also removes the associated quadlet files and reloads systemd.
    """
    compose_path = resolve_compose_path(compose_file)
    compose_data = parse_compose(compose_path)
    service_names = compose_data["service_names"]
    volume_names = compose_data["volume_names"]
    network_names = compose_data["network_names"]
    project = compose_data["project"]
    unit_dir = get_unit_directory()

    if not service_names:
        return

    # Stop services using the appropriate target for the deployment mode
    targets = get_service_targets(compose_data)

    def stop_target(target):
        run_cmd(["systemctl", "--user", "stop", target])

    run_with_progress(targets, stop_target, "Stopped")

    # Disable autostart — include individual container services that may
    # have been enabled for autostart (up.py enables per-service, but
    # get_service_targets() only returns the pod/kube target).
    disable_targets = list(targets)
    if (unit_dir / f"{project}.pod").exists():
        disable_targets += [f"{project}-{svc}" for svc in service_names]
    run_cmd(["systemctl", "--user", "disable", *disable_targets], quiet=True)

    if remove_files:
        # Remove quadlet files derived from the compose file
        files_to_remove = []

        for svc in service_names:
            # In pod/kube mode, files are named {project}-{service}.{ext}
            for ext in (".container", ".build"):
                for pattern in (f"{project}-{svc}{ext}", f"{svc}{ext}"):
                    f = unit_dir / pattern
                    if f.exists():
                        files_to_remove.append(f)
                        break

        for vol in volume_names:
            f = unit_dir / f"{vol}.volume"
            if f.exists():
                files_to_remove.append(f)

        for net in network_names:
            f = unit_dir / f"{net}.network"
            if f.exists():
                files_to_remove.append(f)

        # Remove .pod and .kube files named after the project
        for ext in (".pod", ".kube"):
            f = unit_dir / f"{project}{ext}"
            if f.exists():
                files_to_remove.append(f)

        # Remove Kubernetes YAML generated by --kube mode
        kube_yaml = unit_dir / f"{project}-kube.yaml"
        if kube_yaml.exists():
            files_to_remove.append(kube_yaml)

        for f in files_to_remove:
            run_cmd(["rm", str(f)])

        if files_to_remove:
            run_cmd(["systemctl", "--user", "daemon-reload"])
