"""compose_down - Stop services managed by quadlet files from compose.yaml."""

from utils import (
    get_unit_directory,
    resolve_compose_path,
    parse_compose,
    get_service_targets,
    run_cmd,
)


def compose_down(
    compose_file: str | None = None, remove_files: bool = False, **_kwargs
) -> None:
    """Stop systemd services and optionally remove quadlet files.

    Stops services using the appropriate target (pod, kube, or individual).
    If remove_files is True, also removes the associated quadlet files and reloads systemd.
    """
    compose_path = resolve_compose_path(compose_file)
    compose_data = parse_compose(compose_path)
    service_names = compose_data["service_names"]
    volume_names = compose_data["volume_names"]
    network_names = compose_data["network_names"]
    project = compose_data["project"]
    unit_dir = get_unit_directory()

    if not service_names:
        print("No services defined in compose file.")
        return

    # Stop services using the appropriate target for the deployment mode
    targets = get_service_targets(compose_data)
    print(f"Stopping {', '.join(targets)} ...")
    run_cmd(["systemctl", "--user", "stop", *targets])

    # Also stop individual container services in pod/kube mode
    if targets != service_names:
        run_cmd(["systemctl", "--user", "stop", *service_names])

    if remove_files:
        # Remove quadlet files derived from the compose file
        files_to_remove = []

        for svc in service_names:
            f = unit_dir / f"{svc}.container"
            if f.exists():
                files_to_remove.append(f)

        for vol in volume_names:
            f = unit_dir / f"{vol}.volume"
            if f.exists():
                files_to_remove.append(f)

        for net in network_names:
            f = unit_dir / f"{net}.network"
            if f.exists():
                files_to_remove.append(f)

        # Remove .pod and .kube files named after the project
        for ext in (".pod", ".kube"):
            f = unit_dir / f"{project}{ext}"
            if f.exists():
                files_to_remove.append(f)

        # Remove Kubernetes YAML generated by --kube mode
        kube_yaml = unit_dir / f"{project}-kube.yaml"
        if kube_yaml.exists():
            files_to_remove.append(kube_yaml)

        for f in files_to_remove:
            print(f"Removing {f.name} ...")
            run_cmd(["rm", str(f)])

        if files_to_remove:
            print("Reloading systemd daemon ...")
            run_cmd(["systemctl", "--user", "daemon-reload"])

    print("Done.")
