# generated by datamodel-codegen:
#   filename:  compose-spec.json

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, constr
from typing_extensions import TypeAliasType


class ServiceCgroup(str, Enum):
    host = "host"
    private = "private"


ServiceCpuCount = TypeAliasType(
    "ServiceCpuCount",
    Annotated[int, Field(..., description="Number of usable CPUs.", ge=0)],
)


ServiceCpuPercent = TypeAliasType(
    "ServiceCpuPercent",
    Annotated[
        int, Field(..., description="Percentage of CPU resources to use.", ge=0, le=100)
    ],
)


class ServiceCredentialSpec(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    config: str | None = Field(
        None, description="The name of the credential spec Config to use."
    )
    file: str | None = Field(None, description="Path to a credential spec file.")
    registry: str | None = Field(
        None, description="Path to a credential spec in the Windows registry."
    )


class ServiceDependsOnCondition(str, Enum):
    service_started = "service_started"
    service_healthy = "service_healthy"
    service_completed_successfully = "service_completed_successfully"


class ServiceDependsOn(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    restart: bool | str | None = Field(
        None,
        description="Whether to restart dependent services when this service is restarted.",
    )
    required: bool | None = Field(
        True,
        description="Whether the dependency is required for the dependent service to start.",
    )
    condition: ServiceDependsOnCondition = Field(
        ...,
        description="Condition to wait for. 'service_started' waits until the service has started, 'service_healthy' waits until the service is healthy (as defined by its healthcheck), 'service_completed_successfully' waits until the service has completed successfully.",
    )


class ServiceDevices(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    source: str = Field(..., description="Path on the host to the device.")
    target: str | None = Field(
        None, description="Path in the container where the device will be mapped."
    )
    permissions: str | None = Field(
        None, description="Cgroup permissions for the device (rwm)."
    )


class ServiceExtends(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    service: str = Field(..., description="The name of the service to extend.")
    file: str | None = Field(
        None, description="The file path where the service to extend is defined."
    )


class ServiceProvider(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    type: str = Field(
        ...,
        description="External component used by Compose to manage setup and teardown lifecycle of the service.",
    )
    options: (
        dict[constr(pattern=r"^.+$"), str | float | bool | list[str | float | bool]]
        | None
    ) = Field(None, description="Provider-specific options.")


class ServiceLogging(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    driver: str | None = Field(
        None,
        description="Logging driver to use, such as 'json-file', 'syslog', 'journald', etc.",
    )
    options: dict[constr(pattern=r"^.+$"), str | float | None] | None = Field(
        None, description="Options for the logging driver."
    )


class ServiceModels(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    endpoint_var: str | None = Field(
        None, description="Environment variable set to AI model endpoint."
    )
    model_var: str | None = Field(
        None, description="Environment variable set to AI model name."
    )


ServiceOomScoreAdj = TypeAliasType(
    "ServiceOomScoreAdj",
    Annotated[
        int,
        Field(
            ...,
            description="Tune host's OOM preferences for the container (accepts -1000 to 1000).",
            ge=-1000,
            le=1000,
        ),
    ],
)


class ServicePorts(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    __hash__ = object.__hash__
    name: str | None = Field(
        None, description="A human-readable name for this port mapping."
    )
    mode: str | None = Field(
        None,
        description="The port binding mode, either 'host' for publishing a host port or 'ingress' for load balancing.",
    )
    host_ip: str | None = Field(None, description="The host IP to bind to.")
    target: int | str | None = Field(None, description="The port inside the container.")
    published: str | int | None = Field(None, description="The publicly exposed port.")
    protocol: str | None = Field(None, description="The port protocol (tcp or udp).")
    app_protocol: str | None = Field(
        None,
        description="Application protocol to use with the port (e.g., http, https, mysql).",
    )


class ServiceVolumesType(str, Enum):
    bind = "bind"
    volume = "volume"
    tmpfs = "tmpfs"
    cluster = "cluster"
    npipe = "npipe"
    image = "image"


class ServiceVolumesBindRecursive(str, Enum):
    enabled = "enabled"
    disabled = "disabled"
    writable = "writable"
    readonly = "readonly"


class ServiceVolumesBindSelinux(str, Enum):
    z = "z"
    z_1 = "Z"


class ServiceVolumesBind(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    propagation: str | None = Field(
        None,
        description="The propagation mode for the bind mount: 'shared', 'slave', 'private', 'rshared', 'rslave', or 'rprivate'.",
    )
    create_host_path: bool | str | None = Field(
        None, description="Create the host path if it doesn't exist."
    )
    recursive: ServiceVolumesBindRecursive | None = Field(
        None, description="Recursively mount the source directory."
    )
    selinux: ServiceVolumesBindSelinux | None = Field(
        None,
        description="SELinux relabeling options: 'z' for shared content, 'Z' for private unshared content.",
    )


ServiceVolumesTmpfsSize = TypeAliasType(
    "ServiceVolumesTmpfsSize",
    Annotated[int, Field(..., description="Size of the tmpfs mount in bytes.", ge=0)],
)


class ServiceVolumesTmpfs(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    size: ServiceVolumesTmpfsSize | str | None = Field(
        None, description="Size of the tmpfs mount in bytes."
    )
    mode: float | str | None = Field(
        None, description="File mode of the tmpfs in octal."
    )


class ServiceVolumesImage(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    subpath: str | None = Field(
        None, description="Path within the image to mount instead of the image root."
    )


class Healthcheck(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    disable: bool | str | None = Field(
        None,
        description="Disable any container-specified healthcheck. Set to true to disable.",
    )
    interval: str | None = Field(
        None,
        description="Time between running the check (e.g., '1s', '1m30s'). Default: 30s.",
    )
    retries: float | str | None = Field(
        None,
        description="Number of consecutive failures needed to consider the container as unhealthy. Default: 3.",
    )
    test: str | list[str] | None = Field(
        None,
        description="The test to perform to check container health. Can be a string or a list. The first item is either NONE, CMD, or CMD-SHELL. If it's CMD, the rest of the command is exec'd. If it's CMD-SHELL, the rest is run in the shell.",
    )
    timeout: str | None = Field(
        None,
        description="Maximum time to allow one check to run (e.g., '1s', '1m30s'). Default: 30s.",
    )
    start_period: str | None = Field(
        None,
        description="Start period for the container to initialize before starting health-retries countdown (e.g., '1s', '1m30s'). Default: 0s.",
    )
    start_interval: str | None = Field(
        None,
        description="Time between running the check during the start period (e.g., '1s', '1m30s'). Default: interval value.",
    )


class DevelopmentWatchItemAction(str, Enum):
    rebuild = "rebuild"
    sync = "sync"
    restart = "restart"
    sync_restart = "sync+restart"
    sync_exec = "sync+exec"


class DeploymentRollbackConfigOrder(str, Enum):
    start_first = "start-first"
    stop_first = "stop-first"


class DeploymentRollbackConfig(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    parallelism: int | str | None = Field(
        None,
        description="The number of containers to rollback at a time. If set to 0, all containers rollback simultaneously.",
    )
    delay: str | None = Field(
        None,
        description="The time to wait between each container group's rollback (e.g., '1s', '1m30s').",
    )
    failure_action: str | None = Field(
        None, description="Action to take if a rollback fails: 'continue', 'pause'."
    )
    monitor: str | None = Field(
        None,
        description="Duration to monitor each task for failures after it is created (e.g., '1s', '1m30s').",
    )
    max_failure_ratio: float | str | None = Field(
        None, description="Failure rate to tolerate during a rollback."
    )
    order: DeploymentRollbackConfigOrder | None = Field(
        None,
        description="Order of operations during rollbacks: 'stop-first' (default) or 'start-first'.",
    )


class DeploymentUpdateConfigOrder(str, Enum):
    start_first = "start-first"
    stop_first = "stop-first"


class DeploymentUpdateConfig(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    parallelism: int | str | None = Field(
        None, description="The number of containers to update at a time."
    )
    delay: str | None = Field(
        None,
        description="The time to wait between updating a group of containers (e.g., '1s', '1m30s').",
    )
    failure_action: str | None = Field(
        None,
        description="Action to take if an update fails: 'continue', 'pause', 'rollback'.",
    )
    monitor: str | None = Field(
        None,
        description="Duration to monitor each updated task for failures after it is created (e.g., '1s', '1m30s').",
    )
    max_failure_ratio: float | str | None = Field(
        None, description="Failure rate to tolerate during an update (0 to 1)."
    )
    order: DeploymentUpdateConfigOrder | None = Field(
        None,
        description="Order of operations during updates: 'stop-first' (default) or 'start-first'.",
    )


class DeploymentResourcesLimits(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    cpus: float | str | None = Field(
        None,
        description="Limit for how much of the available CPU resources, as number of cores, a container can use.",
    )
    memory: str | None = Field(
        None,
        description="Limit on the amount of memory a container can allocate (e.g., '1g', '1024m').",
    )
    pids: int | str | None = Field(
        None, description="Maximum number of PIDs available to the container."
    )


class DeploymentRestartPolicy(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    condition: str | None = Field(
        None,
        description="Condition for restarting the container: 'none', 'on-failure', 'any'.",
    )
    delay: str | None = Field(
        None, description="Delay between restart attempts (e.g., '1s', '1m30s')."
    )
    max_attempts: int | str | None = Field(
        None, description="Maximum number of restart attempts before giving up."
    )
    window: str | None = Field(
        None,
        description="Time window used to evaluate the restart policy (e.g., '1s', '1m30s').",
    )


class DeploymentPlacementPreference(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    spread: str | None = Field(
        None,
        description="Spread tasks evenly across values of the specified node label.",
    )


class DeploymentPlacement(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    constraints: list[str] | None = Field(
        None,
        description="Placement constraints for the service (e.g., 'node.role==manager').",
    )
    preferences: list[DeploymentPlacementPreference] | None = Field(
        None, description="Placement preferences for the service."
    )
    max_replicas_per_node: int | str | None = Field(
        None, description="Maximum number of replicas of the service."
    )


class GenericResourcesGenericResourceDiscreteResourceSpec(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    kind: str | None = Field(
        None, description="Type of resource (e.g., 'GPU', 'FPGA', 'SSD')."
    )
    value: float | str | None = Field(
        None, description="Number of resources of this kind to reserve."
    )


class GenericResourcesGenericResource(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    discrete_resource_spec: (
        GenericResourcesGenericResourceDiscreteResourceSpec | None
    ) = Field(None, description="Specification for discrete (countable) resources.")


GenericResources = TypeAliasType(
    "GenericResources",
    Annotated[
        list[GenericResourcesGenericResource],
        Field(
            ...,
            description="User-defined resources for services, allowing services to reserve specialized hardware resources.",
        ),
    ],
)


class GpusGpus(str, Enum):
    all = "all"


class NetworkIpamConfigItem(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    subnet: str | None = Field(
        None, description="Subnet in CIDR format that represents a network segment."
    )
    ip_range: str | None = Field(
        None, description="Range of IPs from which to allocate container IPs."
    )
    gateway: str | None = Field(
        None, description="IPv4 or IPv6 gateway for the subnet."
    )
    aux_addresses: dict[constr(pattern=r"^.+$"), str] | None = Field(
        None, description="Auxiliary IPv4 or IPv6 addresses used by Network driver."
    )


class NetworkIpam(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    driver: str | None = Field(
        None, description="Custom IPAM driver, instead of the default."
    )
    config: list[NetworkIpamConfigItem] | None = Field(
        None, description="List of IPAM configuration blocks."
    )
    options: dict[constr(pattern=r"^.+$"), str] | None = Field(
        None, description="Driver-specific options for the IPAM driver."
    )


class NetworkExternal(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(
        None,
        deprecated=True,
        description="Specifies the name of the external network. Deprecated: use the 'name' property instead.",
    )


class VolumeExternal(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(
        None,
        deprecated=True,
        description="Specifies the name of the external volume. Deprecated: use the 'name' property instead.",
    )


class SecretExternal(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(
        None, description="Specifies the name of the external secret."
    )


class ConfigExternal(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(
        None,
        deprecated=True,
        description="Specifies the name of the external config. Deprecated: use the 'name' property instead.",
    )


class Model(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(None, description="Custom name for this model.")
    model: str = Field(..., description="Language Model to run.")
    context_size: int | None = None
    runtime_flags: list[str] | None = Field(
        None, description="Raw runtime flags to pass to the inference engine."
    )


Command = TypeAliasType(
    "Command",
    Annotated[
        str | list[str] | None,
        Field(
            ...,
            description="Command to run in the container, which can be specified as a string (shell form) or array (exec form).",
        ),
    ],
)


class EnvFileEnvFile(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    path: str = Field(..., description="Path to the environment file.")
    format: str | None = Field(
        None,
        description="Format attribute lets you to use an alternative file formats for env_file. When not set, env_file is parsed according to Compose rules.",
    )
    required: bool | str | None = Field(
        True,
        description="Whether the file is required. If true and the file doesn't exist, an error will be raised.",
    )


EnvFile = TypeAliasType("EnvFile", str | list[str | EnvFileEnvFile])


LabelFile = TypeAliasType("LabelFile", str | list[str])


ListOfStrings = TypeAliasType(
    "ListOfStrings",
    Annotated[set[str], Field(..., description="A list of unique string values.")],
)


ListOrDictListOrDict = TypeAliasType(
    "ListOrDictListOrDict",
    Annotated[set[str], Field(..., description="A list of unique string values.")],
)


ListOrDict = TypeAliasType(
    "ListOrDict",
    Annotated[
        dict[constr(pattern=r".+"), str | float | bool | None] | ListOrDictListOrDict,
        Field(
            ...,
            description="Either a dictionary mapping keys to values, or a list of strings.",
        ),
    ],
)


ExtraHostsExtraHosts = TypeAliasType(
    "ExtraHostsExtraHosts",
    Annotated[
        list[str], Field(..., description="List of IP addresses for the hostname.")
    ],
)


ExtraHostsExtraHosts1 = TypeAliasType(
    "ExtraHostsExtraHosts1",
    Annotated[
        set[str],
        Field(..., description="List of host:IP mappings in the format 'hostname:IP'."),
    ],
)


ExtraHosts = TypeAliasType(
    "ExtraHosts",
    Annotated[
        dict[constr(pattern=r".+"), str | ExtraHostsExtraHosts] | ExtraHostsExtraHosts1,
        Field(
            ...,
            description="Additional hostnames to be defined in the container's /etc/hosts file.",
        ),
    ],
)


class BlkioLimit(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    path: str | None = Field(None, description="Path to the device (e.g., '/dev/sda').")
    rate: int | str | None = Field(
        None, description="Rate limit in bytes per second or IO operations per second."
    )


class BlkioWeight(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    path: str | None = Field(None, description="Path to the device (e.g., '/dev/sda').")
    weight: int | str | None = Field(
        None, description="Relative weight for the device, between 10 and 1000."
    )


class ServiceConfigOrSecretServiceConfigOrSecret(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    source: str | None = Field(
        None,
        description="Name of the config or secret as defined in the top-level configs or secrets section.",
    )
    target: str | None = Field(
        None,
        description="Path in the container where the config or secret will be mounted. Defaults to /<source> for configs and /run/secrets/<source> for secrets.",
    )
    uid: str | None = Field(
        None, description="UID of the file in the container. Default is 0 (root)."
    )
    gid: str | None = Field(
        None, description="GID of the file in the container. Default is 0 (root)."
    )
    mode: float | str | None = Field(
        None,
        description="File permission mode inside the container, in octal. Default is 0444 for configs and 0400 for secrets.",
    )


ServiceConfigOrSecret = TypeAliasType(
    "ServiceConfigOrSecret",
    Annotated[
        list[str | ServiceConfigOrSecretServiceConfigOrSecret],
        Field(
            ...,
            description="Configuration for service configs or secrets, defining how they are mounted in the container.",
        ),
    ],
)


class UlimitsUlimits(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    hard: int | str = Field(
        ...,
        description="Hard limit for the ulimit type. This is the maximum allowed value.",
    )
    soft: int | str = Field(
        ...,
        description="Soft limit for the ulimit type. This is the value that's actually enforced.",
    )


Ulimits = TypeAliasType(
    "Ulimits",
    Annotated[
        dict[constr(pattern=r"^[a-z]+$"), int | str | UlimitsUlimits],
        Field(
            ...,
            description="Container ulimit options, controlling resource limits for processes inside the container.",
        ),
    ],
)


class ServiceBlkioConfig(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    device_read_bps: list[BlkioLimit] | None = Field(
        None, description="Limit read rate (bytes per second) from a device."
    )
    device_read_iops: list[BlkioLimit] | None = Field(
        None, description="Limit read rate (IO per second) from a device."
    )
    device_write_bps: list[BlkioLimit] | None = Field(
        None, description="Limit write rate (bytes per second) to a device."
    )
    device_write_iops: list[BlkioLimit] | None = Field(
        None, description="Limit write rate (IO per second) to a device."
    )
    weight: int | str | None = Field(
        None,
        description="Block IO weight (relative weight) for the service, between 10 and 1000.",
    )
    weight_device: list[BlkioWeight] | None = Field(
        None, description="Block IO weight (relative weight) for specific devices."
    )


class ServiceNetworks(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    aliases: ListOfStrings | None = Field(
        None, description="Alternative hostnames for this service on the network."
    )
    interface_name: str | None = Field(
        None, description="Interface network name used to connect to network"
    )
    ipv4_address: str | None = Field(
        None,
        description="Specify a static IPv4 address for this service on this network.",
    )
    ipv6_address: str | None = Field(
        None,
        description="Specify a static IPv6 address for this service on this network.",
    )
    link_local_ips: ListOfStrings | None = Field(
        None, description="List of link-local IPs."
    )
    mac_address: str | None = Field(
        None, description="Specify a MAC address for this service on this network."
    )
    driver_opts: dict[constr(pattern=r"^.+$"), str | float] | None = Field(
        None, description="Driver options for this network."
    )
    priority: float | None = Field(
        None, description="Specify the priority for the network connection."
    )
    gw_priority: float | None = Field(
        None, description="Specify the gateway priority for the network connection."
    )


class ServiceVolumesVolume(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    labels: ListOrDict | None = Field(
        None, description="Labels to apply to the volume."
    )
    nocopy: bool | str | None = Field(
        None,
        description="Flag to disable copying of data from a container when a volume is created.",
    )
    subpath: str | None = Field(
        None, description="Path within the volume to mount instead of the volume root."
    )


class ServiceVolumes(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    __hash__ = object.__hash__
    type: ServiceVolumesType = Field(
        ...,
        description="The mount type: bind for mounting host directories, volume for named volumes, tmpfs for temporary filesystems, cluster for cluster volumes, npipe for named pipes, or image for mounting from an image.",
    )
    source: str | None = Field(
        None,
        description="The source of the mount, a path on the host for a bind mount, a docker image reference for an image mount, or the name of a volume defined in the top-level volumes key. Not applicable for a tmpfs mount.",
    )
    target: str | None = Field(
        None, description="The path in the container where the volume is mounted."
    )
    read_only: bool | str | None = Field(
        None, description="Flag to set the volume as read-only."
    )
    consistency: str | None = Field(
        None,
        description="The consistency requirements for the mount. Available values are platform specific.",
    )
    bind: ServiceVolumesBind | None = Field(
        None, description="Configuration specific to bind mounts."
    )
    volume: ServiceVolumesVolume | None = Field(
        None, description="Configuration specific to volume mounts."
    )
    tmpfs: ServiceVolumesTmpfs | None = Field(
        None, description="Configuration specific to tmpfs mounts."
    )
    image: ServiceVolumesImage | None = Field(
        None, description="Configuration specific to image mounts."
    )


class DevicesDevice(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    capabilities: ListOfStrings = Field(
        ...,
        description="List of capabilities the device needs to have (e.g., 'gpu', 'compute', 'utility').",
    )
    count: str | int | None = Field(
        None, description="Number of devices of this type to reserve."
    )
    device_ids: ListOfStrings | None = Field(
        None, description="List of specific device IDs to reserve."
    )
    driver: str | None = Field(
        None, description="Device driver to use (e.g., 'nvidia')."
    )
    options: ListOrDict | None = Field(
        None, description="Driver-specific options for the device."
    )


Devices = TypeAliasType(
    "Devices",
    Annotated[
        list[DevicesDevice],
        Field(
            ...,
            description="Device reservations for containers, allowing services to access specific hardware devices.",
        ),
    ],
)


class GpusGpu(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    capabilities: ListOfStrings | None = Field(
        None,
        description="List of capabilities the GPU needs to have (e.g., 'compute', 'utility').",
    )
    count: str | int | None = Field(None, description="Number of GPUs to use.")
    device_ids: ListOfStrings | None = Field(
        None, description="List of specific GPU device IDs to use."
    )
    driver: str | None = Field(None, description="GPU driver to use (e.g., 'nvidia').")
    options: ListOrDict | None = Field(
        None, description="Driver-specific options for the GPU."
    )


Gpus = TypeAliasType("Gpus", GpusGpus | list[GpusGpu])


class Network(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(None, description="Custom name for this network.")
    driver: str | None = Field(
        None,
        description="Specify which driver should be used for this network. Default is 'bridge'.",
    )
    driver_opts: dict[constr(pattern=r"^.+$"), str | float] | None = Field(
        None, description="Specify driver-specific options defined as key/value pairs."
    )
    ipam: NetworkIpam | None = Field(
        None, description="Custom IP Address Management configuration for this network."
    )
    external: NetworkExternal | bool | str | None = Field(
        None,
        description="Specifies that this network already exists and was created outside of Compose.",
    )
    internal: bool | str | None = Field(
        None, description="Create an externally isolated network."
    )
    enable_ipv4: bool | str | None = Field(None, description="Enable IPv4 networking.")
    enable_ipv6: bool | str | None = Field(None, description="Enable IPv6 networking.")
    attachable: bool | str | None = Field(
        None, description="If true, standalone containers can attach to this network."
    )
    labels: ListOrDict | None = Field(
        None, description="Add metadata to the network using labels."
    )


class Volume(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(None, description="Custom name for this volume.")
    driver: str | None = Field(
        None, description="Specify which volume driver should be used for this volume."
    )
    driver_opts: dict[constr(pattern=r"^.+$"), str | float] | None = Field(
        None, description="Specify driver-specific options."
    )
    external: VolumeExternal | bool | str | None = Field(
        None,
        description="Specifies that this volume already exists and was created outside of Compose.",
    )
    labels: ListOrDict | None = Field(
        None, description="Add metadata to the volume using labels."
    )


class Secret(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(None, description="Custom name for this secret.")
    environment: str | None = Field(
        None,
        description="Name of an environment variable from which to get the secret value.",
    )
    file: str | None = Field(
        None, description="Path to a file containing the secret value."
    )
    external: SecretExternal | bool | str | None = Field(
        None,
        description="Specifies that this secret already exists and was created outside of Compose.",
    )
    labels: ListOrDict | None = Field(
        None, description="Add metadata to the secret using labels."
    )
    driver: str | None = Field(
        None, description="Specify which secret driver should be used for this secret."
    )
    driver_opts: dict[constr(pattern=r"^.+$"), str | float] | None = Field(
        None, description="Specify driver-specific options."
    )
    template_driver: str | None = Field(
        None, description="Driver to use for templating the secret's value."
    )


class Config(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: str | None = Field(None, description="Custom name for this config.")
    content: str | None = Field(None, description="Inline content of the config.")
    environment: str | None = Field(
        None,
        description="Name of an environment variable from which to get the config value.",
    )
    file: str | None = Field(
        None, description="Path to a file containing the config value."
    )
    external: ConfigExternal | bool | str | None = Field(
        None,
        description="Specifies that this config already exists and was created outside of Compose.",
    )
    labels: ListOrDict | None = Field(
        None, description="Add metadata to the config using labels."
    )
    template_driver: str | None = Field(
        None, description="Driver to use for templating the config's value."
    )


class ServiceHook(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    command: Command = Field(..., description="Command to execute as part of the hook.")
    user: str | None = Field(None, description="User to run the command as.")
    privileged: bool | str | None = Field(
        None, description="Whether to run the command with extended privileges."
    )
    working_dir: str | None = Field(
        None, description="Working directory for the command."
    )
    environment: ListOrDict | None = Field(
        None, description="Environment variables for the command."
    )


StringOrList = TypeAliasType(
    "StringOrList",
    Annotated[
        str | ListOfStrings,
        Field(..., description="Either a single string or a list of strings."),
    ],
)


class ServiceBuild(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    context: str | None = Field(
        None, description="Path to the build context. Can be a relative path or a URL."
    )
    dockerfile: str | None = Field(
        None, description="Name of the Dockerfile to use for building the image."
    )
    dockerfile_inline: str | None = Field(
        None,
        description="Inline Dockerfile content to use instead of a Dockerfile from the build context.",
    )
    entitlements: list[str] | None = Field(
        None,
        description="List of extra privileged entitlements to grant to the build process.",
    )
    args: ListOrDict | None = Field(
        None,
        description="Build-time variables, specified as a map or a list of KEY=VAL pairs.",
    )
    ssh: ListOrDict | None = Field(
        None,
        description="SSH agent socket or keys to expose to the build. Format is either a string or a list of 'default|<id>[=<socket>|<key>[,<key>]]'.",
    )
    labels: ListOrDict | None = Field(
        None, description="Labels to apply to the built image."
    )
    cache_from: list[str] | None = Field(
        None,
        description="List of sources the image builder should use for cache resolution",
    )
    cache_to: list[str] | None = Field(
        None, description="Cache destinations for the build cache."
    )
    no_cache: bool | str | None = Field(
        None, description="Do not use cache when building the image."
    )
    no_cache_filter: StringOrList | None = Field(
        None, description="Do not use build cache for the specified stages."
    )
    additional_contexts: ListOrDict | None = Field(
        None,
        description="Additional build contexts to use, specified as a map of name to context path or URL.",
    )
    network: str | None = Field(
        None,
        description="Network mode to use for the build. Options include 'default', 'none', 'host', or a network name.",
    )
    provenance: str | bool | None = Field(
        None, description="Add a provenance attestation"
    )
    sbom: str | bool | None = Field(None, description="Add a SBOM attestation")
    pull: bool | str | None = Field(
        None, description="Always attempt to pull a newer version of the image."
    )
    target: str | None = Field(
        None, description="Build stage to target in a multi-stage Dockerfile."
    )
    shm_size: int | str | None = Field(
        None,
        description="Size of /dev/shm for the build container. A string value can use suffix like '2g' for 2 gigabytes.",
    )
    extra_hosts: ExtraHosts | None = Field(
        None, description="Add hostname mappings for the build container."
    )
    isolation: str | None = Field(
        None, description="Container isolation technology to use for the build process."
    )
    privileged: bool | str | None = Field(
        None, description="Give extended privileges to the build container."
    )
    secrets: ServiceConfigOrSecret | None = Field(
        None,
        description="Secrets to expose to the build. These are accessible at build-time.",
    )
    tags: list[str] | None = Field(
        None, description="Additional tags to apply to the built image."
    )
    ulimits: Ulimits | None = Field(
        None, description="Override the default ulimits for the build container."
    )
    platforms: list[str] | None = Field(
        None,
        description="Platforms to build for, e.g., 'linux/amd64', 'linux/arm64', or 'windows/amd64'.",
    )


class DevelopmentWatchItem(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ignore: StringOrList | None = Field(
        None, description="Patterns to exclude from watching."
    )
    include: StringOrList | None = Field(
        None, description="Patterns to include in watching."
    )
    path: str = Field(..., description="Path to watch for changes.")
    action: DevelopmentWatchItemAction = Field(
        ...,
        description="Action to take when a change is detected: rebuild the container, sync files, restart the container, sync and restart, or sync and execute a command.",
    )
    target: str | None = Field(
        None, description="Target path in the container for sync operations."
    )
    exec: ServiceHook | None = Field(
        None,
        description="Command to execute when a change is detected and action is sync+exec.",
    )
    initial_sync: bool | None = Field(
        None,
        description="Ensure that an initial synchronization is done before starting watch mode for sync+x triggers",
    )


class Development(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    watch: list[DevelopmentWatchItem] | None = Field(
        None,
        description="Configure watch mode for the service, which monitors file changes and performs actions in response.",
    )


class DeploymentResourcesReservations(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    cpus: float | str | None = Field(
        None,
        description="Reservation for how much of the available CPU resources, as number of cores, a container can use.",
    )
    memory: str | None = Field(
        None,
        description="Reservation on the amount of memory a container can allocate (e.g., '1g', '1024m').",
    )
    generic_resources: GenericResources | None = Field(
        None, description="User-defined resources to reserve."
    )
    devices: Devices | None = Field(
        None, description="Device reservations for the container."
    )


class DeploymentResources(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    limits: DeploymentResourcesLimits | None = Field(
        None, description="Resource limits for the service containers."
    )
    reservations: DeploymentResourcesReservations | None = Field(
        None, description="Resource reservations for the service containers."
    )


class Deployment(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    mode: str | None = Field(
        None,
        description="Deployment mode for the service: 'replicated' (default) or 'global'.",
    )
    endpoint_mode: str | None = Field(
        None, description="Endpoint mode for the service: 'vip' (default) or 'dnsrr'."
    )
    replicas: int | str | None = Field(
        None, description="Number of replicas of the service container to run."
    )
    labels: ListOrDict | None = Field(
        None, description="Labels to apply to the service."
    )
    rollback_config: DeploymentRollbackConfig | None = Field(
        None, description="Configuration for rolling back a service update."
    )
    update_config: DeploymentUpdateConfig | None = Field(
        None, description="Configuration for updating a service."
    )
    resources: DeploymentResources | None = Field(
        None, description="Resource constraints and reservations for the service."
    )
    restart_policy: DeploymentRestartPolicy | None = Field(
        None, description="Restart policy for the service containers."
    )
    placement: DeploymentPlacement | None = Field(
        None,
        description="Constraints and preferences for the platform to select a physical node to run service containers",
    )


class IncludeInclude(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    path: StringOrList | None = Field(
        None,
        description="Path to the Compose application or sub-project files to include.",
    )
    env_file: StringOrList | None = Field(
        None,
        description="Path to the environment files to use to define default values when interpolating variables in the Compose files being parsed.",
    )
    project_directory: str | None = Field(
        None, description="Path to resolve relative paths set in the Compose file"
    )


Include = TypeAliasType(
    "Include",
    Annotated[
        str | IncludeInclude,
        Field(..., description="Compose application or sub-projects to be included."),
    ],
)


class Service(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    develop: Development | None = None
    deploy: Deployment | None = None
    annotations: ListOrDict | None = None
    attach: bool | str | None = None
    build: str | ServiceBuild | None = Field(
        None, description="Configuration options for building the service's image."
    )
    blkio_config: ServiceBlkioConfig | None = Field(
        None, description="Block IO configuration for the service."
    )
    cap_add: set[str] | None = Field(
        None,
        description="Add Linux capabilities. For example, 'CAP_SYS_ADMIN', 'SYS_ADMIN', or 'NET_ADMIN'.",
    )
    cap_drop: set[str] | None = Field(
        None,
        description="Drop Linux capabilities. For example, 'CAP_SYS_ADMIN', 'SYS_ADMIN', or 'NET_ADMIN'.",
    )
    cgroup: ServiceCgroup | None = Field(
        None,
        description="Specify the cgroup namespace to join. Use 'host' to use the host's cgroup namespace, or 'private' to use a private cgroup namespace.",
    )
    cgroup_parent: str | None = Field(
        None, description="Specify an optional parent cgroup for the container."
    )
    command: Command | None = Field(
        None,
        description="Override the default command declared by the container image, for example 'CMD' in Dockerfile.",
    )
    configs: ServiceConfigOrSecret | None = Field(
        None, description="Grant access to Configs on a per-service basis."
    )
    container_name: str | None = Field(
        None,
        description="Specify a custom container name, rather than a generated default name.",
        pattern="[a-zA-Z0-9][a-zA-Z0-9_.-]+",
    )
    cpu_count: str | ServiceCpuCount | None = Field(
        None, description="Number of usable CPUs."
    )
    cpu_percent: str | ServiceCpuPercent | None = Field(
        None, description="Percentage of CPU resources to use."
    )
    cpu_shares: float | str | None = Field(
        None, description="CPU shares (relative weight) for the container."
    )
    cpu_quota: float | str | None = Field(
        None, description="Limit the CPU CFS (Completely Fair Scheduler) quota."
    )
    cpu_period: float | str | None = Field(
        None, description="Limit the CPU CFS (Completely Fair Scheduler) period."
    )
    cpu_rt_period: float | str | None = Field(
        None,
        description="Limit the CPU real-time period in microseconds or a duration.",
    )
    cpu_rt_runtime: float | str | None = Field(
        None,
        description="Limit the CPU real-time runtime in microseconds or a duration.",
    )
    cpus: float | str | None = Field(
        None,
        description="Number of CPUs to use. A floating-point value is supported to request partial CPUs.",
    )
    cpuset: str | None = Field(
        None, description="CPUs in which to allow execution (0-3, 0,1)."
    )
    credential_spec: ServiceCredentialSpec | None = Field(
        None, description="Configure the credential spec for managed service account."
    )
    depends_on: (
        ListOfStrings
        | dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), ServiceDependsOn]
        | None
    ) = Field(
        None,
        description="Express dependency between services. Service dependencies cause services to be started in dependency order. The dependent service will wait for the dependency to be ready before starting.",
    )
    device_cgroup_rules: ListOfStrings | None = Field(
        None, description="Add rules to the cgroup allowed devices list."
    )
    devices: list[str | ServiceDevices] | None = Field(
        None, description="List of device mappings for the container."
    )
    dns: StringOrList | None = Field(
        None, description="Custom DNS servers to set for the service container."
    )
    dns_opt: set[str] | None = Field(
        None,
        description="Custom DNS options to be passed to the container's DNS resolver.",
    )
    dns_search: StringOrList | None = Field(
        None, description="Custom DNS search domains to set on the service container."
    )
    domainname: str | None = Field(
        None, description="Custom domain name to use for the service container."
    )
    entrypoint: Command | None = Field(
        None,
        description="Override the default entrypoint declared by the container image, for example 'ENTRYPOINT' in Dockerfile.",
    )
    env_file: EnvFile | None = Field(
        None,
        description="Add environment variables from a file or multiple files. Can be a single file path or a list of file paths.",
    )
    label_file: LabelFile | None = Field(
        None,
        description="Add metadata to containers using files containing Docker labels.",
    )
    environment: ListOrDict | None = Field(
        None,
        description="Add environment variables. You can use either an array or a list of KEY=VAL pairs.",
    )
    expose: set[str | float] | None = Field(
        None,
        description="Expose ports without publishing them to the host machine - they'll only be accessible to linked services.",
    )
    extends: str | ServiceExtends | None = Field(
        None, description="Extend another service, in the current file or another file."
    )
    provider: ServiceProvider | None = Field(
        None,
        description="Specify a service which will not be manage by Compose directly, and delegate its management to an external provider.",
    )
    external_links: set[str] | None = Field(
        None,
        description="Link to services started outside this Compose application. Specify services as <service_name>:<alias>.",
    )
    extra_hosts: ExtraHosts | None = Field(
        None,
        description="Add hostname mappings to the container network interface configuration.",
    )
    gpus: Gpus | None = Field(
        None,
        description="Define GPU devices to use. Can be set to 'all' to use all GPUs, or a list of specific GPU devices.",
    )
    group_add: set[str | float] | None = Field(
        None,
        description="Add additional groups which user inside the container should be member of.",
    )
    healthcheck: Healthcheck | None = Field(
        None,
        description="Configure a health check for the container to monitor its health status.",
    )
    hostname: str | None = Field(
        None, description="Define a custom hostname for the service container."
    )
    image: str | None = Field(
        None,
        description="Specify the image to start the container from. Can be a repository/tag, a digest, or a local image ID.",
    )
    init: bool | str | None = Field(
        None,
        description="Run as an init process inside the container that forwards signals and reaps processes.",
    )
    ipc: str | None = Field(
        None,
        description="IPC sharing mode for the service container. Use 'host' to share the host's IPC namespace, 'service:[service_name]' to share with another service, or 'shareable' to allow other services to share this service's IPC namespace.",
    )
    isolation: str | None = Field(
        None,
        description="Container isolation technology to use. Supported values are platform-specific.",
    )
    labels: ListOrDict | None = Field(
        None,
        description="Add metadata to containers using Docker labels. You can use either an array or a list.",
    )
    links: set[str] | None = Field(
        None,
        description="Link to containers in another service. Either specify both the service name and a link alias (SERVICE:ALIAS), or just the service name.",
    )
    logging: ServiceLogging | None = Field(
        None, description="Logging configuration for the service."
    )
    mac_address: str | None = Field(None, description="Container MAC address to set.")
    mem_limit: float | str | None = Field(
        None,
        description="Memory limit for the container. A string value can use suffix like '2g' for 2 gigabytes.",
    )
    mem_reservation: str | int | None = Field(
        None, description="Memory reservation for the container."
    )
    mem_swappiness: int | str | None = Field(
        None, description="Container memory swappiness as percentage (0 to 100)."
    )
    memswap_limit: float | str | None = Field(
        None,
        description="Amount of memory the container is allowed to swap to disk. Set to -1 to enable unlimited swap.",
    )
    network_mode: str | None = Field(
        None,
        description="Network mode. Values can be 'bridge', 'host', 'none', 'service:[service name]', or 'container:[container name]'.",
    )
    models: (
        ListOfStrings
        | dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), ServiceModels | None]
        | None
    ) = Field(
        None,
        description="AI Models to use, referencing entries under the top-level models key.",
    )
    networks: (
        ListOfStrings
        | dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), ServiceNetworks | None]
        | None
    ) = Field(
        None,
        description="Networks to join, referencing entries under the top-level networks key. Can be a list of network names or a mapping of network name to network configuration.",
    )
    oom_kill_disable: bool | str | None = Field(
        None, description="Disable OOM Killer for the container."
    )
    oom_score_adj: str | ServiceOomScoreAdj | None = Field(
        None,
        description="Tune host's OOM preferences for the container (accepts -1000 to 1000).",
    )
    pid: str | None = Field(None, description="PID mode for container.")
    pids_limit: float | str | None = Field(
        None, description="Tune a container's PIDs limit. Set to -1 for unlimited PIDs."
    )
    platform: str | None = Field(
        None,
        description="Target platform to run on, e.g., 'linux/amd64', 'linux/arm64', or 'windows/amd64'.",
    )
    ports: set[float | str | ServicePorts] | None = Field(
        None,
        description="Expose container ports. Short format ([HOST:]CONTAINER[/PROTOCOL]).",
    )
    post_start: list[ServiceHook] | None = Field(
        None,
        description="Commands to run after the container starts. If any command fails, the container stops.",
    )
    pre_stop: list[ServiceHook] | None = Field(
        None,
        description="Commands to run before the container stops. If any command fails, the container stop is aborted.",
    )
    privileged: bool | str | None = Field(
        None, description="Give extended privileges to the service container."
    )
    profiles: ListOfStrings | None = Field(
        None,
        description="List of profiles for this service. When profiles are specified, services are only started when the profile is activated.",
    )
    pull_policy: str | None = Field(
        None,
        description="Policy for pulling images. Options include: 'always', 'never', 'if_not_present', 'missing', 'build', or time-based refresh policies.",
        pattern="always|never|build|if_not_present|missing|refresh|daily|weekly|every_([0-9]+[wdhms])+",
    )
    pull_refresh_after: str | None = Field(
        None,
        description="Time after which to refresh the image. Used with pull_policy=refresh.",
    )
    read_only: bool | str | None = Field(
        None, description="Mount the container's filesystem as read only."
    )
    restart: str | None = Field(
        None,
        description="Restart policy for the service container. Options include: 'no', 'always', 'on-failure', and 'unless-stopped'.",
    )
    runtime: str | None = Field(
        None, description="Runtime to use for this container, e.g., 'runc'."
    )
    scale: int | str | None = Field(
        None, description="Number of containers to deploy for this service."
    )
    security_opt: set[str] | None = Field(
        None, description="Override the default labeling scheme for each container."
    )
    shm_size: float | str | None = Field(
        None,
        description="Size of /dev/shm. A string value can use suffix like '2g' for 2 gigabytes.",
    )
    secrets: ServiceConfigOrSecret | None = Field(
        None, description="Grant access to Secrets on a per-service basis."
    )
    sysctls: ListOrDict | None = Field(
        None,
        description="Kernel parameters to set in the container. You can use either an array or a list.",
    )
    stdin_open: bool | str | None = Field(
        None, description="Keep STDIN open even if not attached."
    )
    stop_grace_period: str | None = Field(
        None,
        description="Time to wait for the container to stop gracefully before sending SIGKILL (e.g., '1s', '1m30s').",
    )
    stop_signal: str | None = Field(
        None, description="Signal to stop the container (e.g., 'SIGTERM', 'SIGINT')."
    )
    storage_opt: dict[str, Any] | None = Field(
        None, description="Storage driver options for the container."
    )
    tmpfs: StringOrList | None = Field(
        None,
        description="Mount a temporary filesystem (tmpfs) into the container. Can be a single value or a list.",
    )
    tty: bool | str | None = Field(
        None, description="Allocate a pseudo-TTY to service container."
    )
    ulimits: Ulimits | None = Field(
        None, description="Override the default ulimits for a container."
    )
    use_api_socket: bool | None = Field(
        None, description="Bind mount Docker API socket and required auth."
    )
    user: str | None = Field(
        None, description="Username or UID to run the container process as."
    )
    uts: str | None = Field(
        None,
        description="UTS namespace to use. 'host' shares the host's UTS namespace.",
    )
    userns_mode: str | None = Field(
        None,
        description="User namespace to use. 'host' shares the host's user namespace.",
    )
    volumes: set[str | ServiceVolumes] | None = Field(
        None,
        description="Mount host paths or named volumes accessible to the container. Short syntax (VOLUME:CONTAINER_PATH[:MODE])",
    )
    volumes_from: set[str] | None = Field(
        None,
        description="Mount volumes from another service or container. Optionally specify read-only access (ro) or read-write (rw).",
    )
    working_dir: str | None = Field(
        None,
        description="The working directory in which the entrypoint or command will be run",
    )


class ComposeSpecification(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    version: str | None = Field(
        None,
        deprecated=True,
        description="declared for backward compatibility, ignored. Please remove it.",
    )
    name: str | None = Field(
        None,
        description="define the Compose project name, until user defines one explicitly.",
    )
    include: list[Include] | None = Field(
        None, description="compose sub-projects to be included."
    )
    services: dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), Service] | None = Field(
        None, description="The services that will be used by your application."
    )
    models: dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), Model] | None = Field(
        None, description="Language models that will be used by your application."
    )
    networks: dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), Network | None] | None = Field(
        None, description="Networks that are shared among multiple services."
    )
    volumes: dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), Volume | None] | None = Field(
        None, description="Named volumes that are shared among multiple services."
    )
    secrets: dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), Secret] | None = Field(
        None, description="Secrets that are shared among multiple services."
    )
    configs: dict[constr(pattern=r"^[a-zA-Z0-9._-]+$"), Config] | None = Field(
        None, description="Configurations that are shared among multiple services."
    )
